# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b537e7b4995a345c5b247560f1d4c471c69cdc6ad5987b5c6b65f8e91daa05f6c4a55ceee6a9d78972e56a574f496c8638eab5031446bca48c7abee93f068599

test:
  secret_key_base: cc803c9d5f831b113a18325c8562da9074c663261b487ed3c01a8e2de6563f3e4a19f2e20a923c84999ee4a38a6964780ab9be16b9c98c89ac5001f586b228c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
